# Generated by Django 5.0.4 on 2024-04-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_libro_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUsuario',
            new_name='id_tipo_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombreApellido',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='categoriausuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categoriausuario',
            name='tipoUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='categoriausuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='categoriausuario',
            name='id_tipo_usuario',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id usuario'),
        ),
    ]
